name: Créer Nouvelle Version de ThonnyTN

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
          
        
      - name: Run Python Script
        run: 'python ./python_last_version.py'         

        
      - name: Download Dependencies
        run: py -m pip download -r "./requirements.txt" --extra-index-url https://riverbankcomputing.com/pypi/simple/ -d depsx64
        
      - name: Ajout des autres whl
        run: cp *.whl depsx64
        
      - name: read python version components
        shell: cmd
        run: |
          for /f "delims=" %%i in (python.version) do set VERSION=%%i
          for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
              set MAJOR=%%a
              set MINOR=%%b
              set PATCH=%%c
          )
          echo %MAJOR%
          echo %MINOR%
          echo %PATCH% 
          echo MAJOR=%MAJOR% >> %GITHUB_ENV%
          echo MINOR=%MINOR% >> %GITHUB_ENV%
          echo PATCH=%PATCH% >> %GITHUB_ENV%
          cat %GITHUB_ENV%
      
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
        
      - uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with: 
          filepath: './simpleInstallerWin10x64.iss /dmajor=${{env.MAJOR}} /dminor=${{env.MINOR}} /dpatch=${{env.PATCH}} /dtag=${{ steps.generate_release_tag.outputs.next_release_tag }}' 
      
          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          files: |
            ./Output/*.exe
          
